---
label: Product
hide_body: true
fields:
- type: text
  name: id
  label: ID
- type: text
  name: title
  label: Title
- type: text
  name: description
  label: Description
- type: text
  name: price
  label: Price
- type: field_group
  name: images
  label: Images
  fields:
  - type: field_group
    name: default
    label: Default
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
  - type: field_group
    name: featured
    label: Featured
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
- type: select
  name: category
  label: Category
  config:
    source:
      type: simple
    options:
    - bebidas
    - cervezas
    - vinos-licores
    - snacks
    - alimentos
    - hogar
    - cigarros
    - higiene-belleza
- type: boolean
  name: featured
  label: Featured
- type: select
  name: section
  label: Section
  config:
    source:
      type: simple
    options:
    - Store
  default: Store
- type: text
  name: layout
  label: Layout
  hidden: true
  default: product
  config:
    required: true
pages:
- products/7-up-gaseosa-lima-limón-2l.md
- products/7-up-gaseosa-lima-limón-3l.md
- products/agua-h2oh-limón-600ml.md
- products/atún-blanco-sardimar-lomo-140g.md
- products/atún-sardimar-trocitos-140g.md
- products/atún-sardimar-vegetales-140g.md
- products/azúcar-doña-maría-2kg.md
- products/bacardi-oro-1l.md
- products/baileys-licor-crema-irlandesa-1l.md
- products/boletas-paquete-ocb.md
- products/bolsa-hielo-3-5-kg.md
- products/cacique-guaro-1l.md
- products/cacique-guaro-365ml.md
- products/café-molido-1820-250gr.md
- products/café-molido-1820-500g.md
- products/café-molido-volio-250g.md
- products/café-molido-volio-500g.md
- products/casillero-del-diablo-carmenere-750ml.md
- products/casillero-diablo-sauvignon-blanc-750ml.md
- products/cerveza-bavaria-chill-lata-350ml.md
- products/cerveza-bavaria-light-lata-350ml.md
- products/cerveza-bohemia-lata-350ml.md
- products/cerveza-imperial-1l.md
- products/cerveza-imperial-6-pack.md
- products/cerveza-imperial-lata-350ml.md
- products/cerveza-imperial-lata-473ml.md
- products/cerveza-imperial-silver-1l.md
- products/cerveza-imperial-silver-6-pack.md
- products/cerveza-imperial-silver-lata-473ml.md
- products/cerveza-imperial-ultra-lata-350ml.md
- products/cerveza-pilsen-1l.md
- products/cerveza-pilsen-lata-350ml.md
- products/cerveza-pilsen-lata-473ml.md
- products/cigarro-derby-duro-box-20-unidades.md
- products/cigarro-marlboro-blue-ice-20-unidades.md
- products/cigarro-marlboro-fusión-20-unidades.md
- products/cigarro-marlboro-gold-original-20-unidades.md
- products/cigarro-viceroy-rojo-20-unidades.md
- products/cigarro-viceroy-suave-20-unidades.md
- products/coca-cola-3l.md
- products/coca-cola-600ml.md
- products/coca-cola-light-2l.md
- products/coca-cola-zero-2-5l.md
- products/condones-durex-clásico-1x3-unidades.md
- products/condones-durex-máximo-placer-1x3-unidades.md
- products/condones-durex-sensitivo-1x3-unidades.md
- products/condones-durex-xl-1x3-unidades.md
- products/cuchara-plástica-link-15-unidades.md
- products/derby-suave-box-20-unidades.md
- products/doritos-nacho-cheese-198g.md
- products/encendedor-bic-grande.md
- products/frijoles-negros-molidos-santa-cruz-medio-400g.md
- products/frijoles-negros-molidos-santa-cruz-medio-800g.md
- products/frijoles-rojos-molidos-santa-cruz-medio-400g.md
- products/frijoles-rojos-molidos-santa-cruz-medio-800g.md
- products/galleta-bokitas-pozuelo-tubo-125g.md
- products/galleta-chiky-chocolate-pozuelo-paquete-12-unidades.md
- products/galleta-oreo-paquete-12-unidades.md
- products/galleta-soda-pozuelo-caja-20-unidades.md
- products/galleta-soda-pozuelo-paquete-8-unidades.md
- products/galleta-yipy-paquete-12-unidades.md
- products/gatorade-bebida-hidratante-blue-berry-600ml.md
- products/hi-c-bebida-de-frutas-1l.md
- products/imperial-silver-lata-350ml.md
- products/jet-red-bebida-energética-600ml.md
- products/johnny-walker-black-and-white-1l.md
- products/l-m-cigarro-morado-forward-20-unidades.md
- products/leche-descremada-dos-pinos-1l.md
- products/leche-deslactosada-delactomy-dos-pinos-1l.md
- products/leche-semidescremada-dos-pinos-1l.md
- products/maní-japonés-rumba-80g.md
- products/maní-pro-con-chile-80g.md
- products/maní-pro-garapiñado-80g.md
- products/maní-pro-limón-y-sal-80g.md
- products/maní-pro-salado-80g.md
- products/papas-lay-s-187g.md
- products/papas-pringles-124g.md
- products/papas-pringles-71g.md
- products/papas-tostadas-kitty-180g.md
- products/pepsi-3l.md
- products/pepsi-light-2-5l.md
- products/pilsen-lata-350-ml-12-und.md
- products/plato-plástico-link-nº-6-15-unidades.md
- products/plato-plástico-link-nº-9-15-unidades.md
- products/plátanos-pro-80g.md
- products/quesitos-116g.md
- products/ron-bacardi-superior-carta-blanca-1l.md
- products/ron-centenario-5-años.md
- products/ron-centenario-7-años.md
- products/rumba-300g.md
- products/salchicha-de-pavo-cinta-azul-380g.md
- products/salsa-chunky-santa-cruz-250g.md
- products/salsa-queso-hellmann-s-caja-1l.md
- products/salsa-queso-tostitos-425-2-g.md
- products/semillas-de-marañon-pro-80gr.md
- products/semillas-mixtas-pro-80gr.md
- products/servilletas-scott-100-unidades.md
- products/tequila-jose-cuervo-oro.md
- products/toallas-sanitarias-kotex-sport-con-alas-10-uds.md
- products/toreaditos-pro-90g.md
- products/tortillas-tostadas-pa-picar-250g.md
- products/tostitos-190g.md
- products/tosty-mix-300g.md
- products/trident-18-unidades.md
- products/tronaditos-tosty-175g.md
- products/tropical-té-blanco-arándano-500ml.md
- products/té-limón-fuze-500ml.md
- products/té-limón-hi-c-1l.md
- products/té-melocotón-cero-tropical-2-5l.md
- products/té-melocotón-fuze-500ml.md
- products/té-melocotón-tropical-3l.md
- products/vino-tinto-frontera-cabernet-sauvignon-750ml.md
- products/vino-tinto-frontera-merlot-750ml.md
- products/whisky-chivas-regal-1l.md
- products/whisky-jb-1l.md
- products/whisky-johnny-walker-rojo-1l.md
- products/whisky-old-parr-1l.md
