---
label: Product
hide_body: true
fields:
- type: text
  name: id
  label: ID
- type: text
  name: title
  label: Title
- type: text
  name: description
  label: Description
- type: text
  name: price
  label: Price
- type: field_group
  name: images
  label: Images
  fields:
  - type: field_group
    name: default
    label: Default
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
  - type: field_group
    name: featured
    label: Featured
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
- type: select
  name: category
  label: Category
  config:
    source:
      type: simple
    options:
    - bebidas
    - cervezas
    - vinos-licores
    - snacks
    - alimentos
    - hogar
    - cigarros
    - higiene-belleza
- type: boolean
  name: featured
  label: Featured
- type: select
  name: section
  label: Section
  config:
    source:
      type: simple
    options:
    - Store
  default: Store
- type: text
  name: layout
  label: Layout
  hidden: true
  default: product
  config:
    required: true
pages:
- products/casillero-diablo-sauvignon-blanc-750ml.md
- products/casillero-del-diablo-carmenere-750ml.md
- products/tropical-té-frío-limón.md
- products/toallas-sanitarias-kotex-sport-con-alas-10-uds.md
- products/tenedor-ecosunrise-10-unidades.md
- products/soldanza-yuquitas-cebolla-135g.md
- products/platos-ecosunrise-n9-10-unidades.md
- products/pilsen-lata-350-ml-12-und.md
- products/pesto-tomate.md
- products/pepsi-black-2-5-l.md
- products/munchies-classic-mix-9-oz.md
- products/imperial-silver-lata-350ml.md
- products/gnocchi-frescos.md
- products/frijoles-molidos.md
- products/doritos-nacho-cheese-198g.md
- products/detergente-ropa-ecos-1l.md
- products/condones-durex-sensitivo-1x3-unidades.md
- products/coca-cola-sin-azúcar-1-5-l.md
- products/l-m-cigarro-morado-forward-20-unidades.md
- products/cigarro-marlboro-gold-original-20-unidades.md
- products/cigarro-marlboro-blue-ice-20-unidades.md
- products/cacique-guaro-365ml.md
- products/bolsa-hielo-3-5-kg.md
- products/bavaria-gold-lt-350ml-6-pack.md
- products/atún-lomo-en-trozos.md
- products/aceite-oliva-extra-virgen.md
